name: 'hevi-action'
description: 'A github action to version helm chart(s)'
author: 'tada5hi'

branding:
    icon: 'heart'
    color: 'black'

inputs:
    directory:
        description: Directory to look for Chart.yaml file(s)
        default: charts
    token:
        description: Token to interact with GitHub
        default: ${{ github.token }}
    package:
        description: Package charts?
        required: true
        default: false
    push:
        description: Push charts to (oci) registry?
        required: true
        default: false
    push_host:
        description: Host of registry
    push_username:
        description: Username of registry
    push_password:
        description: Password of registry
    release:
        description: Release packages?
        required: true
        default: false
    release_branch:
        description: Git branch, where to publish helm repo index.yaml
        required: true
        default: gh-pages
    versionize:
        description: Versionize charts?
        required: false
        default: false
    versionize_version:
        description: Specify a specific version

runs:
    using: node20
    main: dist/index.js
